// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type CoreAssignedCardNumber struct {
	Number string
	Label  string
}

type CorePcbid struct {
	ID     int64
	Pcbid  string
	Status int64
}
