// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: pcbtracker.sql

package db

import (
	"context"
)

const getPcbidStatus = `-- name: GetPcbidStatus :one
SELECT status
FROM core_pcbid
WHERE pcbid = ?
LIMIT 1
`

func (q *Queries) GetPcbidStatus(ctx context.Context, pcbid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPcbidStatus, pcbid)
	var status int64
	err := row.Scan(&status)
	return status, err
}
