server:
  host: "10.1.1.24"
  port: 80
  logging: True

database:
  driver: "sqlite3"
  datasource: "server.db"
  # datasource: ":memory:" # In-memory database (resets on server restart)

eemall_shopserver:
  server_addr: "10.1.1.24"

static:
  expose_folders: false # If true then the a datapath without a filelist can be exposed (not recommended but useful for testing)
  folder:
      -
        path: "/"
        filelist: "static.json"
        datapath: "updates"
