// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Gf8dm7Demomusic struct {
	GameType int64
	Musicid  int64
}

type Gf8dm7Favorite struct {
	GameType int64
	Musicid  int64
	Count    int64
}

type Gf8dm7Message struct {
	ID       int64
	GameType int64
	Enabled  int64
	Message  string
}

type Gf8dm7RankedScore struct {
	ID       int64
	GameType int64
	Musicid  int64
	Seq      int64
	Score    int64
	Flags    int64
	Name     string
}

type Gf8dm7Score struct {
	ID       int64
	GameType int64
	Musicid  int64
	Seq      int64
	Score    int64
}

type Gf8dm7Shop struct {
	GameType int64
	Pref     int64
	Name     string
	Points   int64
}
