// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Gf10dm9CardProfile struct {
	GameType   int64
	Cardid     string
	Name       string
	Pass       string
	Type       int64
	UpdateFlag int64
	Recovery   int64
	Skill      int64
	Expired    int64
}

type Gf10dm9ExProgress struct {
	GameType int64
	Cardid   string
	Exid     int64
	Clear    int64
	Seen     int64
	Serial   int64
}

type Gf10dm9Puzzle struct {
	GameType int64
	Cardid   string
	PuzzleNo int64
	Flags    int64
	Hidden   int64
}

type Gf10dm9Score struct {
	ID       int64
	Cardid   string
	GameType int64
	Netid    int64
	Courseid int64
	SeqMode  int64
	Flags    int64
	Score    int64
	Clear    int64
	Combo    int64
	Skill    int64
	Perc     int64
	Irall    int64
	Ircom    int64
}

type Gf10dm9Shop struct {
	GameType int64
	Sid      string
	Name     string
	Pref     int64
	Points   int64
}
