// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: messages.sql

package db

import (
	"context"
)

const getMessages = `-- name: GetMessages :many
SELECT message
FROM gf8dm7puv_messages
WHERE enabled = 1
AND game_type = ?
`

func (q *Queries) GetMessages(ctx context.Context, gameType int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getMessages, gameType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message string
		if err := rows.Scan(&message); err != nil {
			return nil, err
		}
		items = append(items, message)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
