// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: profile.sql

package db

import (
	"context"
)

const getProfileByCardId = `-- name: GetProfileByCardId :one
SELECT game_type, cardid, name, recovery, styles, hidden, skill, expired
FROM gf9dm8_card_profile
WHERE cardid = ?
AND game_type = ?
`

type GetProfileByCardIdParams struct {
	Cardid   string
	GameType int64
}

func (q *Queries) GetProfileByCardId(ctx context.Context, arg GetProfileByCardIdParams) (Gf9dm8CardProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByCardId, arg.Cardid, arg.GameType)
	var i Gf9dm8CardProfile
	err := row.Scan(
		&i.GameType,
		&i.Cardid,
		&i.Name,
		&i.Recovery,
		&i.Styles,
		&i.Hidden,
		&i.Skill,
		&i.Expired,
	)
	return i, err
}

const updateCardProfile = `-- name: UpdateCardProfile :exec
INSERT INTO gf9dm8_card_profile (game_type, cardid, name, recovery, styles, hidden)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (cardid) DO
UPDATE SET recovery=?4, styles=?5, hidden=?6
`

type UpdateCardProfileParams struct {
	GameType int64
	Cardid   string
	Name     string
	Recovery int64
	Styles   int64
	Hidden   int64
}

func (q *Queries) UpdateCardProfile(ctx context.Context, arg UpdateCardProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateCardProfile,
		arg.GameType,
		arg.Cardid,
		arg.Name,
		arg.Recovery,
		arg.Styles,
		arg.Hidden,
	)
	return err
}

const updatePuzzleProgress = `-- name: UpdatePuzzleProgress :exec
INSERT INTO gf9dm8_puzzles (game_type, cardid, number, flags, out)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (cardid) DO
UPDATE SET number=?3, flags=?4, out=?5
`

type UpdatePuzzleProgressParams struct {
	GameType int64
	Cardid   string
	Number   int64
	Flags    int64
	Out      int64
}

func (q *Queries) UpdatePuzzleProgress(ctx context.Context, arg UpdatePuzzleProgressParams) error {
	_, err := q.db.ExecContext(ctx, updatePuzzleProgress,
		arg.GameType,
		arg.Cardid,
		arg.Number,
		arg.Flags,
		arg.Out,
	)
	return err
}
