// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Gf11dm10CardProfile struct {
	GameType   int64
	Gdid       int64
	Cardid     string
	Irid       string
	Name       string
	Pass       string
	Type       int64
	UpdateFlag int64
	PuzzleNo   int64
	Recovery   int64
	Skill      int64
	Expired    int64
}

type Gf11dm10Land struct {
	GameType int64
	Team     int64
	Round    int64
	Area     int64
	Hidden   int64
	Point    int64
	Spoint   int64
}

type Gf11dm10Puzzle struct {
	GameType int64
	Gdid     int64
	PuzzleNo int64
	Flags    int64
	Hidden   int64
}

type Gf11dm10Score struct {
	ID       int64
	Gdid     int64
	GameType int64
	Netid    int64
	Courseid int64
	SeqMode  int64
	Flags    int64
	Score    int64
	Clear    int64
	Combo    int64
	Skill    int64
	Perc     int64
	Irall    int64
	Ircom    int64
}

type Gf11dm10Shop struct {
	GameType int64
	Sid      string
	Name     string
	Pref     int64
	Points   int64
}
